apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app
  labels:
    app: java-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      # imagePullSecrets:
      # - name: regcred
      containers:
      - name: java-app
        image:  omarriad07/backend:java
        ports:
        - containerPort: 8080 
        
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        env:
        # Define the environment variable
        - name: DB_SERVER # Notice that the case is different here
                                     # from the key name in the ConfigMap.
          valueFrom:
            configMapKeyRef:
              name: db-config        # The ConfigMap this value comes from.
              key: db_server # The key to fetch.

        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: db_user

        - name: DB_PWD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: db_pass

        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: db_root_pass

        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: db_name
        