architecture: replication

auth:
  rootPassword: secret-root-pass
  database: my-app-db
  username: my-user
  password: my-pass

primary:
  persistence:
    enabled: true
    storageClass: gp3
    size: 3Gi

secondary:
  replicaCount: 2
  persistence:
    enabled: true
    storageClass: gp3
    size: 3Gi
  
