apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configName }}
  namespace: {{ .Values.namespace }}
data:
  {{- range $key, $value := .Values.configData}}
  {{ $key }}: {{ $value }}
  {{- end}}
