apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secretData }}
  {{ $key }}: {{ $value | toString | quote }}
  {{- end }}
